name: XSpec
version: '${project.version}'
main: me.xentany.xspec.SpecPlugin
api-version: '1.16'
authors: [x3ntany] # Are you going to add yourself? Just don't delete me.
softdepend: [ProtocolLib]
commands:
  spec: {}